Traceback (most recent call last):
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
response = requests.get(url).json()
print(response)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTimeoutError[0m                              Traceback (most recent call last)
File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/connectionpool.py:536[0m, in [0;36mHTTPConnectionPool._make_request[0;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)[0m
[1;32m    535[0m [38;5;28;01mtry[39;00m:
[0;32m--> 536[0m     response [38;5;241m=[39m [43mconn[49m[38;5;241;43m.[39;49m[43mgetresponse[49m[43m([49m[43m)[49m
[1;32m    537[0m [38;5;28;01mexcept[39;00m (BaseSSLError, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m e:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/connection.py:461[0m, in [0;36mHTTPConnection.getresponse[0;34m(self)[0m
[1;32m    460[0m [38;5;66;03m# Get the response from http.client.HTTPConnection[39;00m
[0;32m--> 461[0m httplib_response [38;5;241m=[39m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mgetresponse[49m[43m([49m[43m)[49m
[1;32m    463[0m [38;5;28;01mtry[39;00m:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/http/client.py:1374[0m, in [0;36mHTTPConnection.getresponse[0;34m(self)[0m
[1;32m   1373[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1374[0m     [43mresponse[49m[38;5;241;43m.[39;49m[43mbegin[49m[43m([49m[43m)[49m
[1;32m   1375[0m [38;5;28;01mexcept[39;00m [38;5;167;01mConnectionError[39;00m:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/http/client.py:318[0m, in [0;36mHTTPResponse.begin[0;34m(self)[0m
[1;32m    317[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[0;32m--> 318[0m     version, status, reason [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_read_status[49m[43m([49m[43m)[49m
[1;32m    319[0m     [38;5;28;01mif[39;00m status [38;5;241m!=[39m CONTINUE:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/http/client.py:279[0m, in [0;36mHTTPResponse._read_status[0;34m(self)[0m
[1;32m    278[0m [38;5;28;01mdef[39;00m [38;5;21m_read_status[39m([38;5;28mself[39m):
[0;32m--> 279[0m     line [38;5;241m=[39m [38;5;28mstr[39m([38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfp[49m[38;5;241;43m.[39;49m[43mreadline[49m[43m([49m[43m_MAXLINE[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;241;43m1[39;49m[43m)[49m, [38;5;124m"[39m[38;5;124miso-8859-1[39m[38;5;124m"[39m)
[1;32m    280[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m(line) [38;5;241m>[39m _MAXLINE:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/socket.py:705[0m, in [0;36mSocketIO.readinto[0;34m(self, b)[0m
[1;32m    704[0m [38;5;28;01mtry[39;00m:
[0;32m--> 705[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_sock[49m[38;5;241;43m.[39;49m[43mrecv_into[49m[43m([49m[43mb[49m[43m)[49m
[1;32m    706[0m [38;5;28;01mexcept[39;00m timeout:

[0;31mTimeoutError[0m: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

[0;31mReadTimeoutError[0m                          Traceback (most recent call last)
File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/requests/adapters.py:486[0m, in [0;36mHTTPAdapter.send[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    485[0m [38;5;28;01mtry[39;00m:
[0;32m--> 486[0m     resp [38;5;241m=[39m [43mconn[49m[38;5;241;43m.[39;49m[43murlopen[49m[43m([49m
[1;32m    487[0m [43m        [49m[43mmethod[49m[38;5;241;43m=[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mmethod[49m[43m,[49m
[1;32m    488[0m [43m        [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m
[1;32m    489[0m [43m        [49m[43mbody[49m[38;5;241;43m=[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mbody[49m[43m,[49m
[1;32m    490[0m [43m        [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mheaders[49m[43m,[49m
[1;32m    491[0m [43m        [49m[43mredirect[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m    492[0m [43m        [49m[43massert_same_host[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m    493[0m [43m        [49m[43mpreload_content[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m    494[0m [43m        [49m[43mdecode_content[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m    495[0m [43m        [49m[43mretries[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmax_retries[49m[43m,[49m
[1;32m    496[0m [43m        [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mtimeout[49m[43m,[49m
[1;32m    497[0m [43m        [49m[43mchunked[49m[38;5;241;43m=[39;49m[43mchunked[49m[43m,[49m
[1;32m    498[0m [43m    [49m[43m)[49m
[1;32m    500[0m [38;5;28;01mexcept[39;00m (ProtocolError, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/connectionpool.py:844[0m, in [0;36mHTTPConnectionPool.urlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    842[0m     new_e [38;5;241m=[39m ProtocolError([38;5;124m"[39m[38;5;124mConnection aborted.[39m[38;5;124m"[39m, new_e)
[0;32m--> 844[0m retries [38;5;241m=[39m [43mretries[49m[38;5;241;43m.[39;49m[43mincrement[49m[43m([49m
[1;32m    845[0m [43m    [49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43merror[49m[38;5;241;43m=[39;49m[43mnew_e[49m[43m,[49m[43m [49m[43m_pool[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43m_stacktrace[49m[38;5;241;43m=[39;49m[43msys[49m[38;5;241;43m.[39;49m[43mexc_info[49m[43m([49m[43m)[49m[43m[[49m[38;5;241;43m2[39;49m[43m][49m
[1;32m    846[0m [43m[49m[43m)[49m
[1;32m    847[0m retries[38;5;241m.[39msleep()

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/util/retry.py:470[0m, in [0;36mRetry.increment[0;34m(self, method, url, response, error, _pool, _stacktrace)[0m
[1;32m    469[0m [38;5;28;01mif[39;00m read [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m [38;5;129;01mor[39;00m method [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_method_retryable(method):
[0;32m--> 470[0m     [38;5;28;01mraise[39;00m [43mreraise[49m[43m([49m[38;5;28;43mtype[39;49m[43m([49m[43merror[49m[43m)[49m[43m,[49m[43m [49m[43merror[49m[43m,[49m[43m [49m[43m_stacktrace[49m[43m)[49m
[1;32m    471[0m [38;5;28;01melif[39;00m read [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/util/util.py:39[0m, in [0;36mreraise[0;34m(tp, value, tb)[0m
[1;32m     38[0m         [38;5;28;01mraise[39;00m value[38;5;241m.[39mwith_traceback(tb)
[0;32m---> 39[0m     [38;5;28;01mraise[39;00m value
[1;32m     40[0m [38;5;28;01mfinally[39;00m:

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/connectionpool.py:790[0m, in [0;36mHTTPConnectionPool.urlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    789[0m [38;5;66;03m# Make the request on the HTTPConnection object[39;00m
[0;32m--> 790[0m response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_request[49m[43m([49m
[1;32m    791[0m [43m    [49m[43mconn[49m[43m,[49m
[1;32m    792[0m [43m    [49m[43mmethod[49m[43m,[49m
[1;32m    793[0m [43m    [49m[43murl[49m[43m,[49m
[1;32m    794[0m [43m    [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mtimeout_obj[49m[43m,[49m
[1;32m    795[0m [43m    [49m[43mbody[49m[38;5;241;43m=[39;49m[43mbody[49m[43m,[49m
[1;32m    796[0m [43m    [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mheaders[49m[43m,[49m
[1;32m    797[0m [43m    [49m[43mchunked[49m[38;5;241;43m=[39;49m[43mchunked[49m[43m,[49m
[1;32m    798[0m [43m    [49m[43mretries[49m[38;5;241;43m=[39;49m[43mretries[49m[43m,[49m
[1;32m    799[0m [43m    [49m[43mresponse_conn[49m[38;5;241;43m=[39;49m[43mresponse_conn[49m[43m,[49m
[1;32m    800[0m [43m    [49m[43mpreload_content[49m[38;5;241;43m=[39;49m[43mpreload_content[49m[43m,[49m
[1;32m    801[0m [43m    [49m[43mdecode_content[49m[38;5;241;43m=[39;49m[43mdecode_content[49m[43m,[49m
[1;32m    802[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mresponse_kw[49m[43m,[49m
[1;32m    803[0m [43m[49m[43m)[49m
[1;32m    805[0m [38;5;66;03m# Everything went great![39;00m

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/connectionpool.py:538[0m, in [0;36mHTTPConnectionPool._make_request[0;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)[0m
[1;32m    537[0m [38;5;28;01mexcept[39;00m (BaseSSLError, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m e:
[0;32m--> 538[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_timeout[49m[43m([49m[43merr[49m[38;5;241;43m=[39;49m[43me[49m[43m,[49m[43m [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m[43m [49m[43mtimeout_value[49m[38;5;241;43m=[39;49m[43mread_timeout[49m[43m)[49m
[1;32m    539[0m     [38;5;28;01mraise[39;00m

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/urllib3/connectionpool.py:370[0m, in [0;36mHTTPConnectionPool._raise_timeout[0;34m(self, err, url, timeout_value)[0m
[1;32m    369[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(err, SocketTimeout):
[0;32m--> 370[0m     [38;5;28;01mraise[39;00m ReadTimeoutError(
[1;32m    371[0m         [38;5;28mself[39m, url, [38;5;124mf[39m[38;5;124m"[39m[38;5;124mRead timed out. (read timeout=[39m[38;5;132;01m{[39;00mtimeout_value[38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m"[39m
[1;32m    372[0m     ) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    374[0m [38;5;66;03m# See the above comment about EAGAIN in Python 3.[39;00m

[0;31mReadTimeoutError[0m: HTTPConnectionPool(host='api.openweathermap.org', port=80): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

[0;31mReadTimeout[0m                               Traceback (most recent call last)
Cell [0;32mIn [3], line 1[0m
[0;32m----> 1[0m response [38;5;241m=[39m [43mrequests[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[43murl[49m[43m)[49m[38;5;241m.[39mjson()
[1;32m      2[0m [38;5;28mprint[39m(response)

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/requests/api.py:73[0m, in [0;36mget[0;34m(url, params, **kwargs)[0m
[1;32m     62[0m [38;5;28;01mdef[39;00m [38;5;21mget[39m(url, params[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m     63[0m     [38;5;124mr[39m[38;5;124;03m"""Sends a GET request.[39;00m
[1;32m     64[0m 
[1;32m     65[0m [38;5;124;03m    :param url: URL for the new :class:`Request` object.[39;00m
[0;32m   (...)[0m
[1;32m     70[0m [38;5;124;03m    :rtype: requests.Response[39;00m
[1;32m     71[0m [38;5;124;03m    """[39;00m
[0;32m---> 73[0m     [38;5;28;01mreturn[39;00m [43mrequest[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mget[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mparams[49m[38;5;241;43m=[39;49m[43mparams[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/requests/api.py:59[0m, in [0;36mrequest[0;34m(method, url, **kwargs)[0m
[1;32m     55[0m [38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we[39;00m
[1;32m     56[0m [38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some[39;00m
[1;32m     57[0m [38;5;66;03m# cases, and look like a memory leak in others.[39;00m
[1;32m     58[0m [38;5;28;01mwith[39;00m sessions[38;5;241m.[39mSession() [38;5;28;01mas[39;00m session:
[0;32m---> 59[0m     [38;5;28;01mreturn[39;00m [43msession[49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/requests/sessions.py:589[0m, in [0;36mSession.request[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[1;32m    584[0m send_kwargs [38;5;241m=[39m {
[1;32m    585[0m     [38;5;124m"[39m[38;5;124mtimeout[39m[38;5;124m"[39m: timeout,
[1;32m    586[0m     [38;5;124m"[39m[38;5;124mallow_redirects[39m[38;5;124m"[39m: allow_redirects,
[1;32m    587[0m }
[1;32m    588[0m send_kwargs[38;5;241m.[39mupdate(settings)
[0;32m--> 589[0m resp [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[43mprep[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43msend_kwargs[49m[43m)[49m
[1;32m    591[0m [38;5;28;01mreturn[39;00m resp

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/requests/sessions.py:703[0m, in [0;36mSession.send[0;34m(self, request, **kwargs)[0m
[1;32m    700[0m start [38;5;241m=[39m preferred_clock()
[1;32m    702[0m [38;5;66;03m# Send the request[39;00m
[0;32m--> 703[0m r [38;5;241m=[39m [43madapter[49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[43mrequest[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    705[0m [38;5;66;03m# Total elapsed time of the request (approximately)[39;00m
[1;32m    706[0m elapsed [38;5;241m=[39m preferred_clock() [38;5;241m-[39m start

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/requests/adapters.py:532[0m, in [0;36mHTTPAdapter.send[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    530[0m     [38;5;28;01mraise[39;00m SSLError(e, request[38;5;241m=[39mrequest)
[1;32m    531[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(e, ReadTimeoutError):
[0;32m--> 532[0m     [38;5;28;01mraise[39;00m ReadTimeout(e, request[38;5;241m=[39mrequest)
[1;32m    533[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(e, _InvalidHeader):
[1;32m    534[0m     [38;5;28;01mraise[39;00m InvalidHeader(e, request[38;5;241m=[39mrequest)

[0;31mReadTimeout[0m: HTTPConnectionPool(host='api.openweathermap.org', port=80): Read timed out. (read timeout=None)
ReadTimeout: HTTPConnectionPool(host='api.openweathermap.org', port=80): Read timed out. (read timeout=None)

