Traceback (most recent call last):
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Make a connection object 'conn' for the MySQL database 'u492297623_student1' on port 3306 at server 145.14.151.151 with username 'u492297623_stud1'
# and password 'Student1'.
import mysql.connector
PWD = open('../../No_sync/password_khliland','r').read()

# Establishing a connection to the MySQL database
connection = mysql.connector.connect(
    host='145.14.151.151',
    port=3306,
    user='u492297623_stud1',
    password=PWD,
    database='u492297623_student1'
)

# Creating a cursor object to execute SQL queries
cursor = connection.cursor()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn [1], line 4[0m
[1;32m      1[0m [38;5;66;03m# Make a connection object 'conn' for the MySQL database 'u492297623_student1' on port 3306 at server 145.14.151.151 with username 'u492297623_stud1'[39;00m
[1;32m      2[0m [38;5;66;03m# and password 'Student1'.[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmysql[39;00m[38;5;21;01m.[39;00m[38;5;21;01mconnector[39;00m
[0;32m----> 4[0m PWD [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../../No_sync/password_khliland[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m[38;5;241m.[39mread()
[1;32m      6[0m [38;5;66;03m# Establishing a connection to the MySQL database[39;00m
[1;32m      7[0m connection [38;5;241m=[39m mysql[38;5;241m.[39mconnector[38;5;241m.[39mconnect(
[1;32m      8[0m     host[38;5;241m=[39m[38;5;124m'[39m[38;5;124m145.14.151.151[39m[38;5;124m'[39m,
[1;32m      9[0m     port[38;5;241m=[39m[38;5;241m3306[39m,
[0;32m   (...)[0m
[1;32m     12[0m     database[38;5;241m=[39m[38;5;124m'[39m[38;5;124mu492297623_student1[39m[38;5;124m'[39m
[1;32m     13[0m )

File [0;32m~/miniforge3/envs/tf_M1/lib/python3.10/site-packages/IPython/core/interactiveshell.py:282[0m, in [0;36m_modified_open[0;34m(file, *args, **kwargs)[0m
[1;32m    275[0m [38;5;28;01mif[39;00m file [38;5;129;01min[39;00m {[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m}:
[1;32m    276[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    277[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIPython won[39m[38;5;124m'[39m[38;5;124mt let you open fd=[39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m by default [39m[38;5;124m"[39m
[1;32m    278[0m         [38;5;124m"[39m[38;5;124mas it is likely to crash IPython. If you know what you are doing, [39m[38;5;124m"[39m
[1;32m    279[0m         [38;5;124m"[39m[38;5;124myou can use builtins[39m[38;5;124m'[39m[38;5;124m open.[39m[38;5;124m"[39m
[1;32m    280[0m     )
[0;32m--> 282[0m [38;5;28;01mreturn[39;00m [43mio_open[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../../No_sync/password_khliland'
FileNotFoundError: [Errno 2] No such file or directory: '../../No_sync/password_khliland'

